apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
resources:
- ../../base
images:
- name: ckshetty4/poc20-app
  newName: ckshetty4/poc20-app
  newTag: 0b766a940f7d4c928f31c78a74863b9dd401e17b
