apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
resources:
- ../../base
images:
- name: ckshetty4/poc20-app
  newName: ckshetty4/poc20-app
  newTag: e9ba6e9c6f54891007412a7b5abe5ec51ee200cf
