apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev
resources:
- ../../base
images:
- name: ckshetty4/poc20-app
  newName: ckshetty4/poc20-app
  newTag: 2183d1c52bec42c3839e89bff0cc1e5b3f1e0b16
