apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev
resources:
- ../../base
images:
- name: ckshetty4/poc20-app
  newName: ckshetty4/poc20-app
  newTag: e9bfe1bb043df4d1050282396ff2c237321ef0ad
