apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev
resources:
- ../../base
images:
- name: ckshetty4/poc20-app
  newName: ckshetty4/poc20-app
  newTag: 88fedc44875f98704ec9ec8b1b32513c6add1f1c
