name: CKShetty GitOps Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets:DOCKERHUB_USERNAME }}
        password: ${{ secrets:DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        push: true
        tags: |
          ckshetty/poc20-app:${{ github.sha }}
          ckshetty/poc20-app:latest

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Update Kustomize Image Tags
      run: |
        cd kustomize/overlays/dev
        kustomize edit set image ckshetty/poc20-app=ckshetty/poc20-app:${{ github.sha }}
        cd ../prod
        kustomize edit set image ckshetty/poc20-app=ckshetty/poc20-app:${{ github.sha }}

    - name: Commit and Push Changes to Git
      run: |
        git config --local user.email "ckshetty-bot@github.com"
        git config --local user.name "CKShetty-CI"
        git add kustomize/overlays/dev/kustomization.yaml kustomize/overlays/prod/kustomization.yaml
        git commit -m "chore: sync tag ${{ github.sha }} [skip ci]"
        git push https://${{ secrets:PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
